### ISSUE TITLE
Observer fails to authenticate

### ISSUE THREAD

**Issue by Montellese** [Montellese/mediaimporter.emby#17]
Sometimes the observer thread fails to authenticate with the Emby server showing the following log message:
```
[mediaimporter.emby] [observer] failed to authenticate with "Emby - Dev" (emby://ae3a593ed7b540c4b8c4ebaadaffd29b/)
```
However following API calls work fine and websocket events are received and handled as well.

**Comment by sualfred** [comment]
Kodi problem. For reference:
https://github.com/Montellese/mediaimporter.emby/issues/18#issuecomment-622668661
