### ISSUE TITLE
Sync issue: Actor artwork urls are not synced

### ISSUE THREAD

**Issue by sualfred** [Montellese/mediaimporter.emby#20]
Not much to say:
Actors are synced perfectly except their artwork. 

Emby is storing the photos with the "primary" key and they should be sycned as "thumb" for actors.

**Comment by Montellese** [comment]
Thanks for the report. Unfortunately this requires changes both in `mediaimporter.emby` (which are trivial) and in Kodi's media import logic and Python API.
