### ISSUE TITLE
Playcount is synced for inprogress but unwatched items

### ISSUE THREAD

**Issue by sualfred** [Montellese/mediaimporter.emby#24]
Issue:
Emby's playcount integer is synced even if the item is just in progress and not 100% watched.

Expected behaviour:
Don't increase the playcount if the item is unwatched or unwatched and in progress.

Reason:
`ListItem.PlayCount` is always empty for unwatched items in Kodi. It's also used by skinners and playlist rules.  It will be increased to `1` once a item or TV show is fully watched and then counted +1 for every new watch.  As soon as you mark the item unwatched the playcount field is empty again. 
Emby is doing it differently and is increasing the playcount everytime. No matter if watched, unwatched or watched state resetted. 

Suggestion:
Ignore Emby's play counter value completely if item is not watched on the server.

**Comment by Montellese** [comment]
So do I understand it correctly that Emby increases the playcount even if the user hasn't finished watching the video? So everytime you start playback of a video playcount is increased independent of whether the user has ever finished watching the video?

**Comment by sualfred** [comment]
Yep, correct. And marking a item as unwatched on Emby doesn't reset the counter.

**Comment by Montellese** [comment]
Actually I never liked that Kodi resets the playcount when marking an item as unwatched ;-) But nothing I can do about it.
