### ISSUE TITLE
Updates on the server are only synchronized on Kodi startup

### ISSUE THREAD

**Issue by sualfred** [Montellese/mediaimporter.emby#27]
Item changes on the server (artwork, progress, playstates, etc) are not recognized until Kodi is restarted and the fast sync trigger kicks in.

(latest Emby server 4.4.1.0)

**Comment by sualfred** [comment]
After another resync it is working again. But this isn't the first time it was "broke".
I'll keep you updated and try to capute a client + server log

**Comment by Montellese** [comment]
This might be related to #17 which I've seen a few times but every time I try to reproduce it everything works fine...

**Comment by sualfred** [comment]
Hmmm... when I faced the issue my daughter was watching on Kodi with E4K. My latest test, when it was working again, she stopped watching.
Can this be related? Maybe E4K was "stealing" the update? (same user)

**Comment by Montellese** [comment]
That shouldn't happen. At least I wouldn't expect it to happen. I'm usually using Emby Web in parallel to testing media importing in Kodi and Emby Web also uses websockets to get the latest changes.

**Comment by sualfred** [comment]
Stopped working again and yeah, I have the observer authentication error on every start of Kodi.
It's the same exception as in https://github.com/Montellese/mediaimporter.emby/issues/18

**Comment by Montellese** [comment]
I have no idea why this is suddenly happening but only every now and then. Either someone has updated the requests module for Kodi Matrix or something has changed in the Emby server.

**Comment by sualfred** [comment]
@Montellese 
Err.... I found a way to replicate. 

With Estuary as skin defined: Authentication always works
With my Embuary skin defined: Autentication fails
With my WIP Embuary2 skin defined: Autentication fails

Every time. Changing the skin from Estuary to another without restarting Kodi doesn't break it as well.

Is it a race condition? Because Estuary isn't as heavy as other skins?

Edit:
Tried to disable `script.skinshortcuts`, `script.embuary.info` and `script.embuary.helper` and none of it os causing it.  There is no other addon used to get these skins running. 
It must be something in the Kodi initialization.

**Comment by Montellese** [comment]
Very odd. I've only ever used Estuary but I only see it randomly. It's also odd because the whole add-on uses the same code to perform authentication so no idea why it would fail for the observer or player but not for synchronization. The main difference there is that observer and player are running as services while the importer is always executed and terminates again.

**Comment by sualfred** [comment]
Kodi Python problem. For reference:
https://github.com/Montellese/mediaimporter.emby/issues/18#issuecomment-622668661
