### ISSUE TITLE
TV Shows sync not completed

### ISSUE THREAD

**Issue by Long-Man** [Montellese/mediaimporter.emby#28]
The sync for tv shows is not completing. Movies and music videos are fine. The log are from a windows machine but I am seeing the same thing on LibreELEC.

https://drive.google.com/file/d/1cljYcyTsCDS4SSmnsWTXpl7_HuRciPIe/view?usp=sharing

**Comment by Montellese** [comment]
Is the progress bar not moving anymore? From the logs it looks like its in the process of importing 40407 episodes which will certainly take a while.

**Comment by Long-Man** [comment]
The progress bar is there for up retrieving and a part of importing then there is a error and it disappears. 40407 wow. Didn't even realized that I had so many. !5 years of ripping.

**Comment by Long-Man** [comment]
This one stopped when importing The Expanse.
https://paste.kodi.tv/ilerorutik.kodi

The Expanse is in two separate libraries. Season 4 is in my library for streaming as it is only available online, Amazon Prime I think. The previous episodes are from disc and DVR. Could that cause a problem?

**Comment by Montellese** [comment]
Hm it's odd because in the logs I see it starting to import all your episodes but it never shows that it stopped or that the thread died. But I'm not 100% sure if we can see a thread dying in windows debug logs.

**Comment by Long-Man** [comment]
Here are the logs from LibreELEC

https://drive.google.com/file/d/1tivbXkAzJza6xhwkiFn96_wsnP7g4Epb/view?usp=sharing

**Comment by Montellese** [comment]
> Here are the logs from LibreELEC
> 
> https://drive.google.com/file/d/1tivbXkAzJza6xhwkiFn96_wsnP7g4Epb/view?usp=sharing

That log is full of HTTP timeouts on both HTTP requests and websocket reads to your Emby server. Sometimes there's also a HTTP 500 error which indicates that something is wrong with the (HTTP) server.
Are you sure your Emby server is running properly?

**Comment by Long-Man** [comment]
I tried to import one or two libraries at a time and that seems to be working. The individual library selected was synced successfully and the items that were there previously from failed syncs were removed. I will complete it by doing 2 or 3 libraries at a time.

BTW. Emby for Kodi has two settings for paging. 
-  [Max Items requested (15)](https://github.com/MediaBrowser/plugin.video.emby/blob/647af73c74c3bd4dbd1e057bd0be4ddcccaa8ae6/resources/lib/downloader.py#L25), and   
-  [Download Threads (3)](https://github.com/MediaBrowser/plugin.video.emby/blob/1c22bf989ae0d168852029322ff172155d3eb927/resources/lib/library.py#L29)

**Comment by Long-Man** [comment]
Thanks for the pointer towards the server. The problem was actually from my NAS. It appears that when the drive is over 80% full there are some timeouts. I don't understand it fully but the problem was solve by adding a nother drive and transferiing files so that no drive was above 80% full.

Thanks again.
