### ISSUE TITLE
Import Boxsets

### ISSUE THREAD

**Issue by Long-Man** [Montellese/mediaimporter.emby#3]
This is what i found in Emby for Kodi with respect to boxsets/movie sets
https://github.com/MediaBrowser/plugin.video.emby/blob/4f9d2d54315a52e8764b43dd97576876e7c89113/resources/lib/library.py#L602

https://github.com/MediaBrowser/plugin.video.emby/blob/4f9d2d54315a52e8764b43dd97576876e7c89113/resources/lib/sync.py#L474

**Comment by Montellese** [comment]
5c999447ecf410c1e34b6f26bd86f456eab4ba5f adds basic support for retrieving `BoxSet`s from the Emby server and matching them to the movies belonging to the `BoxSet`s. But there is no support yet for also synchronizing the `BoxSet`s details like artwork or overview. This will require changes in the media import implementation in Kodi.

**Comment by Long-Man** [comment]
I can confirm that the boxsets have been imported. There are also accurate to the corresponding libraries. ie Kids Movies has boxsets of Kids Movies, Documentaries has boxsets of documentaries etc. And without a filter, one can see all boxsets. Great Job.
You said basic support. What do you consider as missing?

**Comment by Montellese** [comment]
As mentioned it currently only assigns boxsets by name to movies. It does not import artwork or the overview of a boxset into Kodi.

**Comment by Montellese** [comment]
I've started extending Kodi's media import logic to also explicitly import BoxSets / Collections / Movie Sets, see https://github.com/Montellese/xbmc/issues/63. I've created the branch `feature/import_boxsets` in this repository with the necessary changes for Emby. It seems to work i.e. Kodi now also imports the artwork and summary / overview of the BoxSets.

As soon as I've tested it some more and implemented it for `mediaimporter.plex` as well I'll merge it into `master`.

**Comment by Long-Man** [comment]
Sweet. Does it work with the last build or do a need a new kodi build?

**Comment by Long-Man** [comment]
Never mind. Just realized a a new build is required

**Comment by Montellese** [comment]
I've merged the full implementation into `master` and it will be available with the next test-builds and https://github.com/Montellese/mediaimporter.emby/releases/tag/0.0.4.
