### ISSUE TITLE
Emby Context Menu option broke

### ISSUE THREAD

**Issue by sualfred** [Montellese/mediaimporter.emby#30]
Error
`ERROR: [mediaimporter.emby] [context] cannot determine the Emby identifier of "09. Elefantastisch"`

Possible related to https://github.com/Montellese/mediaimporter.emby/commit/6b4e152a6d7c57f24b12192bdf696c820c7fde18

**Comment by Montellese** [comment]
Yes changing the default unique ID from `emby` to `imdb` (or whatever) results in Kodi not loading all the unique IDs for common list items. The unique IDs are only loaded on demand when e.g. opening the video info dialog or when playing the item.

I either need to find another way to store the emby ID in a `ListItem` which is always available or I need to manually load the unique IDs if I need them.

**Comment by Montellese** [comment]
This also affects resetting the resume point of an in-progress video.

**Comment by Montellese** [comment]
I've reverted the commit which didn't set `"emby"` as the default unique ID. This should solve these issues.

**Comment by sualfred** [comment]
Ok, but shouldn't this issue be opened as reminder once you finished your DB concept to access all of them? Because the Emby ID should not be the default ID as discussed.
