### ISSUE TITLE
Mixed Libraries and Mediaimport 

### ISSUE THREAD

**Issue by ntilagoa** [Montellese/mediaimporter.emby#31]
Hi
Great work so far.
Any chance that in future MediaImport supports mixed libraries.?
I and I suppose many others use mixed libraries on emby (ex: anime , which contains both movies and tv shows). Emby for kodi + embuary skin handles this very well , and if Mediaimport supports this it will be a game changer for many users.
Thank you

**Comment by Montellese** [comment]
Can mixed libraries contain any combination of media types? I'm guessing that it should be possible to e.g. import all movies from a mixed library and all tvshows from a mixed library but Kodi is not capable of showing the two media types together in a single library so I'm not sure if it would be a major gain?

**Comment by sualfred** [comment]
Embuary does this in a "hacky" way. It checks if a tag is existing in the movie and tvshow table and just shows a hardcoded hub that fetches both.
You also could force it by creating custom tags in Emby. That's what I'm doing for documentaries. All of them are in my regular "movie" and "tvshow" library but I have added "docu" as tag for these items.

@Montellese 
Mixed library can be everything. In E4K we just fetch the movies and tvshows of them and add them with the same tag to Kodi.

**Comment by Montellese** [comment]
Please give the `improvement/mixed_libraries` branch a try.
