### ISSUE TITLE
Refresh Item

### ISSUE THREAD

**Issue by Long-Man** [Montellese/mediaimporter.emby#5]
This seems to the the refresh routine in Emby for Kodi
https://github.com/MediaBrowser/plugin.video.emby/blob/4f9d2d54315a52e8764b43dd97576876e7c89113/libraries/emby/core/api.py#L299

**Comment by Montellese** [comment]
Looking at the code from Emby for Kodi I'm confused: I always assumed you wanted to manually synchronize the metadata from the Emby server with the Kodi library. But the code from Emby for Kodi looks like it triggers a refresh of the metadata on the Emby server.

Obviously if something changes during the refresh on the Emby server it would automatically lead to the changes being sent to mediaimporter.emby and then being synchronized to the Kodi library. So the result in Kodi might actually be the same but in Emby the item might have changed its metadata.

Which feature did you have in mind?

**Comment by Long-Man** [comment]
I was thinking of it as you described. It triggers a single item refresh in emby that is automatically picked up by the importer. It can be for a movie, tv show, season, episode etc
I have listed some scenarios in which it is useful, this is another that i had omitted. A library scan in Emby first scans the files into the library then attempt to get meta data from online. If the meta data site is down (thetvdb is down sometimes) then the item remains in the library with the filename as title. When I encounter this I can trigger the refresh which then pulls the metadata from online and pass it to Kodi.

**Comment by Montellese** [comment]
Okay. Thanks for the clarification.

I actually ended up implementing both features i.e. from the context menu you can tell Emby to refresh the metadata of an item (which will be propagated to Kodi) and you can tell mediaimporter.emby to re-synchronize a specific item (e.g. in case some update from Emby was lost / missed).

**Comment by Long-Man** [comment]
Thank you
